// <auto-generated />
using System;
using ContactApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactApp.Model.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContactId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnName("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("City")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnName("Company")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Image")
                        .HasColumnName("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnName("PersonalNumber")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("ProfileId")
                        .HasColumnName("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnName("State")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("WorkNumber")
                        .IsRequired()
                        .HasColumnName("WorkNumber")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("ContactId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Calle 1 123",
                            Birthdate = new DateTime(2020, 7, 6, 3, 7, 32, 254, DateTimeKind.Local).AddTicks(9291),
                            City = "Mar del Plata",
                            Company = "Santander Rio",
                            Email = "juan.gonzales@gmail.com",
                            Image = "image1",
                            Name = "Juan Gonzales",
                            PersonalNumber = "5411527714",
                            ProfileId = 1,
                            State = "Buenos Aires",
                            WorkNumber = "5411527754"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Belgrano 550",
                            Birthdate = new DateTime(2020, 7, 4, 3, 7, 32, 255, DateTimeKind.Local).AddTicks(9425),
                            City = "Mendoza",
                            Company = "Galeno",
                            Email = "guillermo.garcia@gmail.com",
                            Image = "image2",
                            Name = "Guillermo Garcia",
                            PersonalNumber = "5411635449",
                            ProfileId = 2,
                            State = "Mendoza",
                            WorkNumber = "5411635489"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Av Libertador 1700",
                            Birthdate = new DateTime(2020, 7, 1, 3, 7, 32, 255, DateTimeKind.Local).AddTicks(9538),
                            City = "Capital Federal",
                            Company = "Arcor",
                            Email = "martin.mendoza@gmail.com",
                            Image = "image3",
                            Name = "Martin Mendoza",
                            PersonalNumber = "5411526328",
                            ProfileId = 3,
                            State = "Buenos Aires",
                            WorkNumber = "5411526358"
                        });
                });

            modelBuilder.Entity("ContactApp.Model.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProfileId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            Name = "User"
                        },
                        new
                        {
                            ProfileId = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            ProfileId = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ContactApp.Model.Contact", b =>
                {
                    b.HasOne("ContactApp.Model.Profile", "Profile")
                        .WithMany("Contacts")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK_contact_profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
